"""
Build and dependency management.
"""
[tool.poetry]
name = "ethereal-sdk"
version = "0.1.0"
description = "Agentic AI Toolkit"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
